version: '3'
services:
  app-001:
    image: web-app-1
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-app-001
    ports:
      - 3000:3000

  app-002:
    image: web-app-2
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-app-002
    ports:
      - 3000:3001
